In [1]:
import pandas as pd

iris_filename = "iris.csv"
iris = pd.read_csv(
    iris_filename,
    sep=",",
    decimal=".",
    header=None,
    names=["sepal_length", "sepal_width", "petal_length", "petal_width", "target"],
)

In [5]:
iris.values

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-setosa']
 [4.8 3.1 

In [6]:
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
target           object
dtype: object

In [12]:
import numpy as np

array = np.arange(5).reshape(1, 5)
print(array)
x = array + 1
print(x)
y = array * array
print(y)

[[0 1 2 3 4]]
[[1 2 3 4 5]]
[[ 0  1  4  9 16]]


In [14]:
array2 = np.array([1, 2, 3, 4, 5] * 5).reshape(5, 5)
array3 = array2.T
array2 * array3

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [16]:
print(np.sum(array2, axis=0))
print(np.sum(array2, axis=1))
print(np.average(array2, axis=0))
print(np.average(array2))

[ 5 10 15 20 25]
[15 15 15 15 15]
[1. 2. 3. 4. 5.]
3.0


In [23]:
array4 = np.arange(5 * 5, dtype="float").reshape(5, 5)
coefs = np.array([1.0, 0.5, 0.5, 0.5, 0.5])
coefs_matrix = np.column_stack((coefs, coefs[::-1]))
coefs_matrix

array([[1. , 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 1. ]])

In [24]:
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html
np.dot(array4, coefs)

array([ 5., 20., 35., 50., 65.])

In [25]:
np.dot(coefs, array4)

array([25., 28., 31., 34., 37.])

In [26]:
np.dot(array4, coefs_matrix)

array([[ 5.,  7.],
       [20., 22.],
       [35., 37.],
       [50., 52.],
       [65., 67.]])

In [29]:
# Indexation (it create data view not copy)
array5 = np.arange(100, dtype=int).reshape(10, 10)
array5[2:9:2, :]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [30]:
array5[2:9:2, 5:]

array([[25, 26, 27, 28, 29],
       [45, 46, 47, 48, 49],
       [65, 66, 67, 68, 69],
       [85, 86, 87, 88, 89]])

In [32]:
array5[2:9:2, 5::-1]

array([[25, 24, 23, 22, 21, 20],
       [45, 44, 43, 42, 41, 40],
       [65, 64, 63, 62, 61, 60],
       [85, 84, 83, 82, 81, 80]])

In [35]:
mask = (array5 >= 20) & (array5 <= 90) & ((array5 / 10.0) % 1 >= 0.5)
array5[mask]

array([25, 26, 27, 28, 29, 35, 36, 37, 38, 39, 45, 46, 47, 48, 49, 55, 56,
       57, 58, 59, 65, 66, 67, 68, 69, 75, 76, 77, 78, 79, 85, 86, 87, 88,
       89])

In [36]:
row_index = [1, 1, 2, 7]
col_index = [0, 2, 4, 8]
array5[row_index, col_index]

array([10, 12, 24, 78])

In [40]:
# add data (2 dimensions)
dataset = np.arange(50).reshape(10, 5)
single_line = np.arange(1 * 5).reshape(1, 5)
few_lines = np.arange(3 * 5).reshape(3, 5)

new_data = np.vstack((dataset, single_line))
print(new_data)
new_data = np.vstack((new_data, few_lines))
print(new_data)

# alternative  w_data = np.vstack((new_data,single_line, few_lines))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [ 0  1  2  3  4]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
# add data (3 dimensions)
np.dstack((dataset * 1, dataset * 2, dataset * 3))

array([[[  0,   0,   0],
        [  1,   2,   3],
        [  2,   4,   6],
        [  3,   6,   9],
        [  4,   8,  12]],

       [[  5,  10,  15],
        [  6,  12,  18],
        [  7,  14,  21],
        [  8,  16,  24],
        [  9,  18,  27]],

       [[ 10,  20,  30],
        [ 11,  22,  33],
        [ 12,  24,  36],
        [ 13,  26,  39],
        [ 14,  28,  42]],

       [[ 15,  30,  45],
        [ 16,  32,  48],
        [ 17,  34,  51],
        [ 18,  36,  54],
        [ 19,  38,  57]],

       [[ 20,  40,  60],
        [ 21,  42,  63],
        [ 22,  44,  66],
        [ 23,  46,  69],
        [ 24,  48,  72]],

       [[ 25,  50,  75],
        [ 26,  52,  78],
        [ 27,  54,  81],
        [ 28,  56,  84],
        [ 29,  58,  87]],

       [[ 30,  60,  90],
        [ 31,  62,  93],
        [ 32,  64,  96],
        [ 33,  66,  99],
        [ 34,  68, 102]],

       [[ 35,  70, 105],
        [ 36,  72, 108],
        [ 37,  74, 111],
        [ 38,  76, 114],
        [ 3